'use strict';

/**
 * Deception engine: dispatches detected threats to the matching trap and reports
 * every fired trap to the telemetry service via a single HTTP call.
 */

const { faker } = require('@faker-js/faker');

const dataBomb = require('../traps/dataBomb');
const tarpit = require('../traps/tarpit');
const fakeLoginTrap = require('../traps/fakeLogin');
const honeyToken = require('../traps/honeyToken');
const sandboxXSS = require('../traps/sandboxXSS');
const infiniteRedirect = require('../traps/infiniteRedirect');

const TRAP_TYPES = require('@evation/shared-constants');
const { getAttackerIp, attackLog } = require('@evation/shared-utils');
const telemetry = require('../utils/telemetryClient');
const legacyBreachSession = require('../utils/legacyBreachSession');
const sqliDumpRotation = require('../utils/sqliDumpRotation');
const {
  isHoneyTokenAcknowledged,
  extractPresentedToken,
  consumeRate,
} = require('../utils/honeyTokenFlow');
const { listHoneyTokens, getHoneyToken } = require('@evation/shared-constants/honeyTokens');
const { PATHS: DP } = require('../config/deceptionPaths');
function usernameFromSqliPayload(req) {
  const raw = String(req.body?.username || req.query?.username || '').trim();
  const m = raw.match(/^([a-zA-Z0-9._-]+)/);
  return (m && m[1]) || 'admin';
}

function buildFakeCredentialRows() {
  const dbUri = getHoneyToken('hr-db-uri');
  const hrKey = getHoneyToken('hr-api-key');
  const rows = [
    { id: 1, username: 'admin', password: 'InnoTech!2024', hash: '$2y$10$7eL8fakeadminhashplaceholder', role: 'administrator' },
    { id: 2, username: 'hr_svc', password: 'svc_HR_9k2m', hash: '$2y$10$9fakehrhashvalue000000000', role: 'service' },
    { id: 3, username: 'j.doe', password: 'Welcome123!', hash: '$2y$10$3fakedoehash00000000000000', role: 'employee' },
  ];
  // Planted: a service_config row leaks the honey DB URI + HR integration key
  // (this is how the SQLi credential dump becomes a honey-token discovery path).
  if (dbUri) {
    rows.push({ id: rows.length + 1, username: 'service_config', password: dbUri.value, hash: '—', role: 'config' });
  }
  if (hrKey) {
    rows.push({ id: rows.length + 1, username: 'hr_integration', password: hrKey.value, hash: '—', role: 'api_key' });
  }
  for (let i = 0; i < 7; i++) {
    const u = faker.internet.username().toLowerCase().replace(/[^a-z0-9._-]/g, '');
    rows.push({
      id: rows.length + 1,
      username: u,
      password: faker.internet.password({ length: 12 }),
      hash: `$2y$10$${faker.string.alphanumeric(22)}`,
      role: faker.helpers.arrayElement(['employee', 'manager', 'readonly']),
    });
  }
  return rows;
}

/** Masked integrations list for the (non-minting) integrations page. */
function maskedIntegrations() {
  return listHoneyTokens().map((t) => {
    const value = String(t.value);
    const masked = value.length > 8 ? `${value.slice(0, 8)}…${value.slice(-4)}` : '••••';
    return {
      service: t.service,
      owner: t.email,
      tokenType: t.tokenType,
      scopes: t.scopes || [],
      maskedKey: masked,
      status: 'active',
    };
  });
}

/** Realistic leaked `.env` content carrying the planted honey-token values. */
function buildLeakedEnv() {
  const hrKey = getHoneyToken('hr-api-key');
  const dbUri = getHoneyToken('hr-db-uri');
  const jwt = getHoneyToken('monitoring-jwt');
  return [
    '# InnoTech HR portal — production environment',
    '# Generated by deploy pipeline. DO NOT COMMIT.',
    'NODE_ENV=production',
    'PORT=8080',
    '',
    '# HR integration API',
    `HR_API_KEY=${hrKey ? hrKey.value : ''}`,
    'HR_API_BASE=https://hr.innotech.io/internal/api/v1',
    '',
    '# Read replica (reporting/exports)',
    `DATABASE_URL=${dbUri ? dbUri.value : ''}`,
    '',
    '# Monitoring agent (service JWT)',
    `MONITORING_JWT=${jwt ? jwt.value : ''}`,
    'SESSION_SECRET=4f9a1c7e8b2d6f30a1c5e9b7d3f60a82',
    '',
  ].join('\n');
}

/** Realistic leaked `.git/config` with committed AWS credentials. */
function buildLeakedGitConfig() {
  const aws = getHoneyToken('aws-backup-key');
  return [
    '[core]',
    '\trepositoryformatversion = 0',
    '\tfilemode = true',
    '\tbare = false',
    '[remote "origin"]',
    '\turl = https://github.com/innotech-it/hr-portal.git',
    '\tfetch = +refs/heads/*:refs/remotes/origin/*',
    '[branch "main"]',
    '\tremote = origin',
    '\tmerge = refs/heads/main',
    '# leftover deploy credentials (rotate!)',
    '[innotech "backup"]',
    `\taws_access_key_id = ${aws ? aws.value : ''}`,
    `\taws_secret_access_key = ${aws ? aws.secret : ''}`,
    '\tregion = us-east-1',
    '\tbucket = innotech-prod-backups',
    '',
  ].join('\n');
}

/** Serve a planted leaked artifact as raw text (looks like an exposed file). */
exports.serveEnvLeak = async (req, res) => {
  await report(TRAP_TYPES.RECON, req, {
    payload: JSON.stringify({ action: 'leaked_env_accessed', path: req.originalUrl || req.path }),
    wasted_time_ms: 0,
  });
  res.type('text/plain').send(buildLeakedEnv());
};

exports.serveGitConfigLeak = async (req, res) => {
  await report(TRAP_TYPES.RECON, req, {
    payload: JSON.stringify({ action: 'leaked_git_config_accessed', path: req.originalUrl || req.path }),
    wasted_time_ms: 0,
  });
  res.type('text/plain').send(buildLeakedGitConfig());
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Stringify the relevant request parts for storage as AttackEvent.payload. */
function extractPayload(req) {
  const candidate =
    req.body?.payload ??
    req.query?.payload ??
    req.body ??
    req.query ??
    {};
  try {
    return typeof candidate === 'string' ? candidate : JSON.stringify(candidate);
  } catch {
    return String(candidate);
  }
}

function buildEventFields(req, opts = {}) {
  return {
    traceId: req.traceId,
    method: req.method,
    path: req.originalUrl || req.path,
    userAgent: req.headers['user-agent'],
    referer: req.headers.referer || req.headers.referrer,
    fingerprint: req.attackerFingerprint || {},
    handoffFrom: opts.handoffFrom,
    xssTier: opts.xssTier,
    secondaryTraps: opts.secondaryTraps ?? req.threatInfo?.secondary ?? [],
  };
}

/**
 * Centralised reporter: every trap calls this on entry (and again on exit for
 * streaming traps so wasted_time_ms / bytes_sent are accurate). A single HTTP
 * call to telemetry persists the event, upserts the profile, and broadcasts.
 */
async function report(trapType, req, opts = {}) {
  const eventData = {
    attackerIp: getAttackerIp(req),
    trapType,
    payload: opts.payload ?? extractPayload(req),
    startTime: opts.startTime,
    wasted_time_ms: opts.wasted_time_ms,
    bytes_sent: opts.bytes_sent || 0,
    ...buildEventFields(req, opts),
  };

  return telemetry.reportAttack(eventData);
}

exports.report = report;

// ─── Public Dispatch ─────────────────────────────────────────────────────────

/**
 * Handler for direct visits to the decoy console path. Routes to the right trap
 * when a threat is already flagged, otherwise serves the fake admin dashboard.
 */
exports.dispatch = async (req, res) => {
  const threat = req.threatInfo?.type;

  switch (threat) {
    case TRAP_TYPES.SQLI: return exports.handleDatabaseExport(req, res);
    case TRAP_TYPES.XSS:  return exports.renderSandboxXSS(req, res);
    case TRAP_TYPES.PATH_TRAVERSAL: return exports.renderFileViewer(req, res);
    case TRAP_TYPES.SSRF: return exports.renderFetchStatus(req, res);
    case TRAP_TYPES.SCANNER: return exports.serveScannerTarpit(req, res);
    case TRAP_TYPES.RECON:
    case TRAP_TYPES.HONEY_TOKEN:
      return exports.renderAdminDashboard(req, res);
    default:              return exports.renderAdminDashboard(req, res);
  }
};

// ─── Individual Trap Handlers ────────────────────────────────────────────────

exports.serveDataBomb = async (req, res) => {
  // dataBomb reports its own bytes_sent / wasted_time_ms when the stream ends
  return dataBomb.stream(req, res, { report });
};

exports.renderDatabaseConsole = async (req, res) => {
  const legacyUser = legacyBreachSession.readBreachUser(req);
  res.render('decoy/database-console', {
    legacyUser,
    query: req.query?.q || 'SELECT * FROM users',
    lastError: req.query?.err ? String(req.query.err) : '',
    withBase: req.withBase || ((p) => p),
    dp: DP,
  });
};

exports.handleDatabaseExport = async (req, res) => {
  const startTime = Date.now();
  const legacyUser = legacyBreachSession.readBreachUser(req);
  const wantsDump =
    req.query?.export === 'credentials' ||
    req.method === 'POST' ||
    (req.body?.query && /select|from|users/i.test(String(req.body.query)));

  if (!wantsDump) {
    return exports.renderDatabaseConsole(req, res);
  }

  if (sqliDumpRotation.shouldShowCredentialDump(req)) {
    const rows = buildFakeCredentialRows();
    await report(TRAP_TYPES.SQLI, req, {
      startTime,
      wasted_time_ms: Date.now() - startTime,
      bytes_sent: rows.length * 80,
      payload: JSON.stringify({ action: 'credential_dump', rows: rows.length }),
    });
    return res.render('decoy/credential-dump', {
      legacyUser,
      rows,
      rowCount: rows.length,
      withBase: req.withBase || ((p) => p),
      dp: DP,
    });
  }

  return tarpit.hold(req, res, { report });
};

/** SQLi on employee login → fake “bypass succeeded” legacy page. */
exports.handoffSqliBypassLogin = async (req, res) => {
  const name = legacyBreachSession.establishBreachSession(res, { username: usernameFromSqliPayload(req) });
  attackLog.warn('GATEWAY', 'sqli_bypass_illusion', {
    trap: TRAP_TYPES.SQLI,
    username: name,
    ...attackLog.requestFields(req),
  });
  await report(TRAP_TYPES.SQLI, req, {
    payload: JSON.stringify({ handoff: 'sqli_bypass_illusion', username: name }),
    handoffFrom: 'employee_login',
    wasted_time_ms: 0,
  });
  return res.redirect(302, req.withBase(`${DP.legacySignIn}?sqli=bypass&next=db`));
};

exports.fakeLogin = async (req, res) => {
  return fakeLoginTrap.handle(req, res, { report });
};

exports.logoutLegacyAdmin = (req, res) => {
  legacyBreachSession.clearBreachSession(res);
  attackLog.info('GATEWAY', 'legacy_admin_signout', { ...attackLog.requestFields(req) });
  return res.redirect(302, req.withBase('/login'));
};

exports.renderFakeLoginPage = (req, res) => {
  const fromBrute = req.query?.from === 'brute';
  if (fromBrute) {
    legacyBreachSession.establishBreachSession(res, { username: req.query?.username || 'administrator' });
    return res.redirect(302, req.withBase(`${DP.console}?breach=legacy`));
  }

  const sqliBypass = req.query?.sqli === 'bypass';
  const showDbHint = req.query?.next === 'db';
  const legacyUser = legacyBreachSession.readBreachUser(req);

  res.render('decoy/fake-login', {
    error: req.query?.error || '',
    username: legacyUser?.username || req.query?.username || '',
    withBase: req.withBase || ((p) => p),
    legacy: false,
    sqliBypass,
    showDbHint,
    legacyUser: sqliBypass ? legacyUser : null,
    dp: DP,
  });
};

/**
 * Integrations page — realistic admin view. Keys are NOT minted or shown here
 * (they are provisioned via CI/Vault and only the masked suffix is visible).
 * The working credentials leak through planted artifacts (.env, .git/config,
 * SQLi dump), so this page is no longer the token source.
 */
exports.serveHoneyToken = async (req, res) => {
  await report(TRAP_TYPES.RECON, req, {
    payload: JSON.stringify({ action: 'viewed_integrations' }),
    wasted_time_ms: 0,
  });
  return res.render('decoy/honey-token', {
    integrations: maskedIntegrations(),
    legacyUser: legacyBreachSession.readBreachUser(req),
    withBase: req.withBase || ((p) => p),
    dp: DP,
  });
};

// ─── Realistic honey-token API ───────────────────────────────────────────────

/** Resolve forensic context for a honey-token API request. */
function honeyUseCtx(req, outcome) {
  return {
    attackerIp: getAttackerIp(req),
    networkContext: 'HTTP',
    method: req.method,
    path: req.originalUrl || req.path,
    userAgent: req.headers['user-agent'],
    outcome,
    traceId: req.traceId,
  };
}

/** Authorize a honey-token API call: resolves provenance, scope, and rate limit. */
function authorizeHoneyApi(req, requiredScope) {
  const presented = extractPresentedToken(req);
  const entry = req.honeyToken || null;

  if (!entry) {
    return { ok: false, status: 401, error: 'invalid_token', presented };
  }

  const rate = consumeRate(entry.value || presented);
  if (rate.limited) {
    return { ok: false, status: 429, error: 'rate_limited', entry, rate, presented };
  }
  if (requiredScope && !(entry.scopes || []).includes(requiredScope)) {
    return { ok: false, status: 403, error: 'insufficient_scope', entry, rate, presented };
  }
  return { ok: true, status: 200, entry, rate, presented };
}

function applyRateHeaders(res, rate) {
  if (!rate) return;
  res.setHeader('X-RateLimit-Limit', String(rate.limit));
  res.setHeader('X-RateLimit-Remaining', String(rate.remaining));
}

/** Record usage + report an AttackEvent for a honey-token API outcome. */
async function logHoneyApiUse(req, { entry, presented, outcome, action, extra = {} }) {
  if (entry) {
    await honeyToken.recordUsage(entry.value || presented, honeyUseCtx(req, outcome));
  }
  await report(TRAP_TYPES.HONEY_TOKEN, req, {
    payload: JSON.stringify({
      action,
      outcome,
      service: entry?.service,
      tokenType: entry?.tokenType,
      scope: entry?.scopes,
      leakSource: entry?.leakSource,
      ...extra,
    }),
    wasted_time_ms: 0,
  });
}

/** Send a realistic 401 with WWW-Authenticate (logs only if a credential was tried). */
async function denyUnauthorized(req, res, action) {
  res.setHeader('WWW-Authenticate', 'Bearer realm="InnoTech API", error="invalid_token"');
  const presented = extractPresentedToken(req);
  if (presented) {
    // A credential was tried but is not a known honey token (wrong/expired key).
    await report(TRAP_TYPES.HONEY_TOKEN, req, {
      payload: JSON.stringify({ action, outcome: 401, reason: 'invalid_key' }),
      wasted_time_ms: 0,
    });
  } else {
    attackLog.info('GATEWAY', 'honey_api_unauthenticated', { action, ...attackLog.requestFields(req) });
  }
  return res.status(401).json({
    error: 'invalid_token',
    error_description: 'The access token is missing, invalid, or expired.',
  });
}

/**
 * Fake HR export — behaves like a real, scoped, paginated, rate-limited API when
 * a stolen integration key is used. Returns 401/403/429 like a real service.
 */
exports.serveHoneyTokenApiExport = async (req, res) => {
  const auth = authorizeHoneyApi(req, 'hr:read');

  if (auth.status === 401) return denyUnauthorized(req, res, 'api_hr_export');

  if (auth.status === 429) {
    applyRateHeaders(res, auth.rate);
    res.setHeader('Retry-After', String(auth.rate.retryAfterSec));
    if (auth.rate.firstLimited) {
      await logHoneyApiUse(req, { entry: auth.entry, presented: auth.presented, outcome: 429, action: 'api_hr_export' });
    }
    return res.status(429).json({ error: 'rate_limited', error_description: 'API rate limit exceeded.' });
  }

  if (auth.status === 403) {
    applyRateHeaders(res, auth.rate);
    await logHoneyApiUse(req, {
      entry: auth.entry, presented: auth.presented, outcome: 403, action: 'api_hr_export',
      extra: { required_scope: 'hr:read' },
    });
    return res.status(403).json({
      error: 'insufficient_scope',
      error_description: 'This token is not authorized for scope "hr:read".',
      scope: 'hr:read',
    });
  }

  // 200 — paginated employee export.
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 25));
  const total = 247;
  const totalPages = Math.ceil(total / limit);
  const start = (page - 1) * limit;
  const count = Math.max(0, Math.min(limit, total - start));

  const employees = Array.from({ length: count }, (_, i) => {
    const id = start + i + 1;
    const username = faker.internet.username().toLowerCase().replace(/[^a-z0-9._-]/g, '');
    return {
      id,
      username,
      email: faker.internet.email({ provider: 'innotech.io' }),
      password: faker.internet.password({ length: 12 }),
      passwordHash: `$2y$10$${faker.string.alphanumeric(22)}`,
      role: faker.helpers.arrayElement(['employee', 'manager', 'readonly', 'service']),
      department: faker.commerce.department(),
    };
  });

  applyRateHeaders(res, auth.rate);
  res.setHeader('X-Total-Count', String(total));
  const base = req.withBase ? req.withBase(DP.hrExport) : DP.hrExport;
  const links = [];
  if (page < totalPages) links.push(`<${base}?page=${page + 1}&limit=${limit}>; rel="next"`);
  if (page > 1) links.push(`<${base}?page=${page - 1}&limit=${limit}>; rel="prev"`);
  if (links.length) res.setHeader('Link', links.join(', '));

  await logHoneyApiUse(req, {
    entry: auth.entry, presented: auth.presented, outcome: 200, action: 'api_hr_export',
    extra: { page, limit, returned: employees.length },
  });

  return res.json({
    success: true,
    source: 'hr_read_replica',
    exportedAt: new Date().toISOString(),
    pagination: { page, limit, total, totalPages },
    count: employees.length,
    employees,
  });
};

/** Fake S3-style storage listing for the leaked AWS backup key (scope s3:list). */
exports.serveHoneyTokenStorageList = async (req, res) => {
  const auth = authorizeHoneyApi(req, 's3:list');

  if (auth.status === 401) return denyUnauthorized(req, res, 'api_storage_list');

  if (auth.status === 429) {
    applyRateHeaders(res, auth.rate);
    res.setHeader('Retry-After', String(auth.rate.retryAfterSec));
    if (auth.rate.firstLimited) {
      await logHoneyApiUse(req, { entry: auth.entry, presented: auth.presented, outcome: 429, action: 'api_storage_list' });
    }
    return res.status(429).json({ error: 'rate_limited', error_description: 'API rate limit exceeded.' });
  }

  if (auth.status === 403) {
    applyRateHeaders(res, auth.rate);
    await logHoneyApiUse(req, {
      entry: auth.entry, presented: auth.presented, outcome: 403, action: 'api_storage_list',
      extra: { required_scope: 's3:list' },
    });
    return res.status(403).json({
      error: 'insufficient_scope',
      error_description: 'This token is not authorized for scope "s3:list".',
      scope: 's3:list',
    });
  }

  const objects = Array.from({ length: 12 }, () => ({
    key: `backups/${faker.date.recent({ days: 30 }).toISOString().slice(0, 10)}/${faker.system.fileName()}.tar.gz`,
    size: faker.number.int({ min: 1_000_000, max: 5_000_000_000 }),
    lastModified: faker.date.recent({ days: 30 }).toISOString(),
    storageClass: faker.helpers.arrayElement(['STANDARD', 'GLACIER', 'STANDARD_IA']),
  }));

  applyRateHeaders(res, auth.rate);
  await logHoneyApiUse(req, {
    entry: auth.entry, presented: auth.presented, outcome: 200, action: 'api_storage_list',
    extra: { returned: objects.length },
  });

  return res.json({
    bucket: 'innotech-prod-backups',
    region: 'us-east-1',
    keyCount: objects.length,
    isTruncated: false,
    objects,
  });
};

exports.renderSandboxXSS = async (req, res) => {
  return sandboxXSS.render(req, res, { report });
};

// ─── Dynamic Admin Dashboard (Faker) ─────────────────────────────────────────

exports.renderFileViewer = async (req, res) => {
  const requested = String(req.query?.file || req.query?.path || '../../../etc/passwd');
  await report(TRAP_TYPES.PATH_TRAVERSAL, req, {
    payload: JSON.stringify({ file: requested }),
    wasted_time_ms: 0,
  });
  const legacyUser = legacyBreachSession.readBreachUser(req);
  res.render('decoy/file-viewer', {
    requested,
    legacyUser,
    withBase: req.withBase || ((p) => p),
    dp: DP,
  });
};

exports.renderFetchStatus = async (req, res) => {
  const target = String(req.query?.url || req.body?.url || 'http://169.254.169.254/latest/meta-data/');
  await report(TRAP_TYPES.SSRF, req, {
    payload: JSON.stringify({ url: target }),
    wasted_time_ms: 0,
  });
  if (req.accepts('json') && !req.accepts('html')) {
    return res.json({
      success: true,
      fetched: target,
      instanceId: 'i-0f4e8b2c9a1d3e5f7',
      region: 'us-east-1',
      iam: { role: 'InnoTech-HR-Prod-Role', credentials: '***REDACTED***' },
      note: 'Internal metadata bridge — legacy integration',
    });
  }
  const legacyUser = legacyBreachSession.readBreachUser(req);
  return res.render('decoy/fetch-status', {
    target,
    legacyUser,
    withBase: req.withBase || ((p) => p),
    dp: DP,
  });
};

exports.serveInfiniteRedirect = async (req, res) => {
  return infiniteRedirect.handle(req, res, {
    report,
    mountPath: '/internal/archives',
  });
};

exports.serveInfiniteRedirectLegacy = async (req, res) => {
  return infiniteRedirect.handle(req, res, {
    report,
    mountPath: '/admin/v1/backup',
  });
};

exports.serveScannerTarpit = async (req, res) => {
  return tarpit.hold(req, res, {
    trapType: TRAP_TYPES.SCANNER,
    report: (t, r, opts) =>
      report(t, r, {
        ...opts,
        payload: JSON.stringify({ scanner_ua: r.headers['user-agent'] }),
      }),
  });
};

exports.renderAdminDashboard = async (req, res) => {
  const skipReport =
    req.threatInfo?.type === TRAP_TYPES.HONEY_TOKEN ||
    req.query?.breach === 'legacy' ||
    isHoneyTokenAcknowledged(req);

  if (!skipReport) {
    const trapType = req.threatInfo?.type === TRAP_TYPES.HONEY_TOKEN
      ? TRAP_TYPES.HONEY_TOKEN
      : TRAP_TYPES.RECON;
    await report(trapType, req, { payload: req.originalUrl || req.path });
  }

  // Fresh fake company on every request — defeats automated scrapers
  const employees = Array.from({ length: 12 }, () => ({
    id:         faker.string.uuid(),
    name:       faker.person.fullName(),
    email:      faker.internet.email({ provider: 'innotech.io' }),
    department: faker.commerce.department(),
    salary:     faker.number.int({ min: 55000, max: 180000 }),
    joined:     faker.date.past({ years: 5 }).toLocaleDateString(),
    role:       faker.person.jobTitle(),
  }));

  const stats = {
    totalEmployees: faker.number.int({ min: 200, max: 800 }),
    revenue:        `$${faker.number.int({ min: 1, max: 50 })}M`,
    openTickets:    faker.number.int({ min: 5, max: 120 }),
    uptime:         `${faker.number.float({ min: 98.5, max: 99.99, fractionDigits: 2 })}%`,
  };

  const breachUser = legacyBreachSession.readBreachUser(req);
  const breachFlash = req.query?.breach === 'legacy' || !!breachUser;
  const tokenAck =
    isHoneyTokenAcknowledged(req) || req.threatInfo?.type === TRAP_TYPES.HONEY_TOKEN;

  res.render('decoy/admin-dashboard', {
    company:   'InnoTech Corp',
    employees,
    stats,
    generated: new Date().toISOString(),
    withBase:  req.withBase || ((p) => p),
    user: breachUser,
    breachFlash,
    breachUsername: breachUser?.username || 'administrator',
    tokenAck,
    dp: DP,
  });
};
