version = 1

test_patterns = [
  "**/*.test.js",
  "**/*.test.ts",
  "**/*.test.tsx",
  "**/tests/**",
]

exclude_patterns = [
  "**/node_modules/**",
  "**/.next/**",
  "**/dist/**",
  "**/build/**",
  "**/coverage/**",
  "admin-panel/next-env.d.ts",
]

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  module_system = "es-modules"
  dialect = "typescript"
  environment = ["nodejs", "browser"]
  cyclomatic_complexity_threshold = "critical"
  skip_doc_coverage = [
    "function-declaration",
    "function-expression",
    "arrow-function-expression",
    "method-definition",
  ]
  dependency_file_paths = [
    "package.json",
    "admin-panel/package.json",
    "packages/db-schemas/package.json",
    "packages/shared-constants/package.json",
    "packages/shared-utils/package.json",
    "services/innotech-gateway/package.json",
    "services/logging-data-extraction/package.json",
  ]
