// Trap types matching the honeypot architecture from the PDF spec
const TRAP_TYPES = {
    SQL_INJECTION: 'SQL_INJECTION',
    XSS: 'XSS',
    PATH_TRAVERSAL: 'PATH_TRAVERSAL',
    COMMAND_INJECTION: 'COMMAND_INJECTION',
    HONEY_TOKEN: 'HONEY_TOKEN',
    FAKE_ADMIN: 'FAKE_ADMIN',
    TARPIT: 'TARPIT',
    DECOY_FILE: 'DECOY_FILE',
    SSH_HONEYPOT: 'SSH_HONEYPOT',
    SMTP_HONEYPOT: 'SMTP_HONEYPOT'
};

module.exports = TRAP_TYPES;
